name: Compile

concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: develop
  pull_request:
    branches: develop

jobs:
  make-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX (LuaLateX)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          texlive_version: 2025
          latexmk_use_lualatex: true

      - name: Move PDFs to public directory
        run: |
          mv main.pdf docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    if: github.ref == 'refs/heads/develop'
    needs: make-pdf
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4